### ISSUE TITLE
try/catch is invalid

### ISSUE THREAD

**Issue by fullee** [trzsz/trzsz.js#6]
https://github.com/trzsz/trzsz.js/blob/7681a63a4cafa460949bec253f277466f9ee5d52/src/filter.ts#L190

My environment is browser but it goes to nodejs code

![image](https://user-images.githubusercontent.com/11188837/169924868-f789564a-2e2d-4793-aa4f-d38edb2ca3dc.png)

**Comment by lonnywong** [comment]
Did you define a `require` function?

If the `node:fs` module is available, it is recommended that you implement `chooseSendFiles ` and `chooseSaveDirectory`.

Otherwise, maybe I should add an option to force it to run in browser.

**Comment by fullee** [comment]
I guess this function doesn't work，`isRunningInBrowser`.

**Comment by lonnywong** [comment]
Can you test `require("fs")` and `require.resolve("fs")` on the console?

<img width="351" alt="image" src="https://user-images.githubusercontent.com/20320324/169932703-e47d2ce9-f982-4972-af3f-011eef65e318.png">

**Comment by fullee** [comment]
I run npm install again and it works,very confused 😓

**Comment by fullee** [comment]
Reasons for Feels like vite compilation
![image](https://user-images.githubusercontent.com/11188837/169960300-ca1de532-eb8b-47e1-9f70-3795b8790fa8.png)

![image](https://user-images.githubusercontent.com/11188837/169960502-004e4a47-f625-4764-8d1e-6c4da2255310.png)
