### ISSUE TITLE
Add trzsz support to ttyd

### ISSUE THREAD

**Issue by tianyuanhao** [trzsz/trzsz.js#8]
Related to tsl0922/ttyd#905

I'm not familiar with JavaScript, would the author be willing to add trzsz support to [ttyd](https://github.com/tsl0922/ttyd)?

**Comment by lonnywong** [comment]
@tianyuanhao 
I'm glad to hear that. It may be easier if the author of ttyd wants to support. If there's anything I can help with, I'd love to do it.
